config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    get '/login', :to => 'devise/sessions#new', :as => :login
    post '/login_user', :to => 'devise/sessions#create', :as => :login_user
    get '/logout', :to => 'devise/sessions#destroy', :as => :destroy_session
    post '/request_reset', :to => 'devise/passwords#edit', :as => :request_reset
    get '/change_password', :to => 'devise/passwords#new', :as => :change_password
  end
  root to: 'homes#index' # Home page
  get '/back', to: 'homes#index' # Back button option
  # Bangalore dropdown navigation bar*
  get '/moving_to', to: 'homes#moving_to'
  # Moving to Bangalore Links
    # Start
  get '/healthcare', to: 'homes#healthcare', as: 'healthcare'
  get '/schools', to: 'homes#schools', as: 'schools'
  get '/residency', to: 'homes#residency', as: 'residency'
  get '/accomodations', to: 'homes#accomodations', as: 'accomodations'
  get '/safe_environments', to: 'homes#safe_environments', as: 'safe_environments'
  get '/transportation', to: 'homes#transportation', as: 'transportation'
  get '/banking', to: 'homes#banking', as: 'banking'
  get '/pets', to: 'homes#pets', as: 'pets'
    # end
  # Bangalore dropdown nav bar*
  get '/life_in', to: 'homes#life_in'
    # Start
  get '/pests', to: 'homes#pests', as: 'pests'
  get '/shopping', to: 'homes#shopping', as: 'shopping'
  get '/activities', to: 'homes#activities', as: 'activities'
  get '/festivals', to: 'homes#festivals', as: 'festivals'
    # end
  # Membership dropdown navigation bar*
  get '/new_member', to: 'homes#new_member' # New Memeber Info, Benefits, etc.
    # Start
  get '/member_info', to: 'homes#member_info', as: 'member_info'
  get '/new_member_app', to: 'homes#new_member_app', as: 'new_member_app'
  get '/benefits', to: 'homes#benefits', as: 'benefits'
    # end
  get '/renew_membership', to: 'homes#renew_membership' # Renew membership here
  get '/renew_form', to: 'homes#renew_form', as: 'renew_form'
  # Membership dropdown nav bar*
  get '/publication', to: 'homes#publication'
    # Start
  get '/member_magazine', to: 'homes#member_magazine', as: 'member_magazine'
  get '/in_and_out', to: 'homes#in_and_out', as: 'in_and_out'
  get '/greeting_cards', to: 'homes#greeting_cards', as: 'greeting_cards'
  get '/other_publication', to: 'homes#other_publication', as: 'other_publication'
    # End
  # Membership dropdown nav bar*
  get '/volunteer', to: 'homes#volunteer'
    # Start
  get '/job_openings', to: 'homes#job_openings', as: 'job_openings'
  get '/volunteer_form', to: 'homes#volunteer_form', as: 'volunteer_form'
    # end
    # Membership nav bar*
  get '/public_calendar', to: 'homes#public_calendar', as: 'public_calendar'
  # Our Work dropdown navigation bar*
  get '/charities', to: 'homes#charities'
    # Start
  get '/charities_list', to: 'homes#charities_list', as: 'charities_list'
  get '/charity_map', to: 'homes#chairty_map', as: 'charity_map'
    # end
  # Our Work dropdown navigation bar*
  get '/contributions', to: 'homes#contributions'
    # Start
  get '/contribution_reports', to: 'homes#reports', as: 'reports'
  get '/report2016', to: 'homes#report2016', as: 'report2016'
  get '/report2017', to: 'homes#report2017', as: 'report2017'
    # end
  # Our Work dropdown navigation bar*
  get '/fundraising', to: 'homes#fundraising'
    # Start
  get '/fundraising_news', to: 'homes#fundraising_news', as: 'fundraising_news'
  get '/fundraising_reports', to: 'homes#fundraising_reports', as: 'fundraising_reports'
    # end
  # Our Work dropdown navigation bar*
  get '/ssg', to: 'homes#ssg' # Social Support Group
    # Start
  get '/ssg_news', to: 'homes#ssg_news', as: 'ssg_news'
  get '/ssg_stories', to: 'homes#ssg_stories', as: 'ssg_stories'
    # end
  # Members Only dropdown navigation bar*
  get '/chat_room', to: 'chat_rooms#index'
  get '/calendar', to: 'calendars#index'
  get '/board_members', to: 'users#board_members'
  # About options bottom of page
  get '/owc_club_info', to: 'homes#owc_club_info'
  get '/mission_statement', to: 'homes#mission_statement'
  get '/journey', to: 'homes#journey'
  # Contact Us bottom of page
  get '/contact', to: 'homes#contact'
  # match '/contacts', to: 'contacts#new', via: 'get'
  # resources "contacts", only: [:new, :create]
  get '/profile', to: 'users#profile'

  get '/payments', to: 'payments#index'
  		resources :payments do
		collection {post :import}
	end

  # resources :users do
  #   get :autocomplete_:recipients_:first_name,:last_name, :on => :collection
  # end
  # get '/import', to: 'users#index'
  get '/autofill', to: 'users#index'
  # resources :messages
  # resources :conversations, only: [:index, :show, :destroy]



  mount ActionCable.server => '/cable'

# mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  # authorize_resource :class => false

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:notice] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user).order("created_at ASC")
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end


  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end


  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img id="message_pic" class="media-object" src="/assets/messaging_test.jpg" alt="Tiger">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.full_name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.full_name, p.id ] }, {}, {multiple: true, class: "chosen-select form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

<%= javascript_include_tag 'conversations', 'data-turbolinks-track': 'reload' %>

app/views/conversations/_messages.html.erb
<%= stylesheet_link_tag 'mailbox', media: 'all' %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="/assets/bootstrap.min.css" media="all" rel="stylesheet" />
<link href="css/bootstrap.min.css" rel="stylesheet">
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img id="message_pic" class="media-object" src="/assets/messaging_test.jpg" alt="Tiger">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.full_name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <font style="margin-top: 25px; font-size: 17px;"><%= message.body %></font>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<link rel="stylesheet" href="mailbox.css">
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', id: 'trash', method: :post%>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>
<script>
$('#foo').confirmModal({backdrop: 'static', keyboard: false});
</script>